Objective-J/ObjJAcornCompiler.js
Tests/Objective-J/Preprocessor/OutputTests/Misc/ref-self.j
Tests/Objective-J/Preprocessor/OutputTests/Misc/ref-self.js
Tests/Objective-J/Preprocessor/OutputTests/OutputTest.j

This fixes #2268
Thanks @kevin-xu

Fixed: @ref did not generate self.x for an ivar x

---

AppKit/CPDatePicker/_CPDatePickerClock.j
AppKit/CPPasteboard.j
AppKit/CPPopover.j
AppKit/CPSegmentedControl.j
AppKit/CPShadow.j
AppKit/CPSound.j
AppKit/CPWebView.j
AppKit/CPWindowController.j
AppKit/CoreGraphics/CGContext.j
Foundation/CPInvocation.j
Foundation/CPNotification.j

Previously, some warnings were raised when compiling Cappuccino.

Fixed: warnings when compiling cappuccino

---

AppKit/CPTableView.j
Tests/AppKit/CPTableViewTest.j

Fix for CPTableView issue #2310: wrong textcolor in unfocused table.

---

Foundation/CPPredicate/CPExpression.j
Foundation/CPPredicate/_CPAggregateExpression.j
Foundation/CPPredicate/_CPBlockExpression.j
Foundation/CPPredicate/_CPConditionalExpression.j
Foundation/CPPredicate/_CPConstantValueExpression.j
Foundation/CPPredicate/_CPExpression.j
Foundation/CPPredicate/_CPFunctionExpression.j
Foundation/CPPredicate/_CPPredicate.j
Foundation/CPPredicate/_CPSetExpression.j
Foundation/CPPredicate/_CPSubqueryExpression.j
Foundation/CPPredicate/_CPVariableExpression.j
Tests/Foundation/CPPredicateTest.j

• CPExpression +expressionForBlock:arguments:
• CPExpression +expressionForConditional:trueExpression:falseExpression:
With tests.

New CPExpression constructors

---

AppKit/CPSearchField.j
Tests/Manual/CPSearchField/AppController.j

… now that it is available. This removes a dirty hack.

CPSearchField: use CPMenuItem -setIndentationLevel: 

---

AppKit/CPPopUpButton.j
Tests/AppKit/CPPopUpButtonTest.j

Fixed: First popup item is always selected if selected binding value is set before content binding value

---

AppKit/CPCollectionView.j
Tests/AppKit/CPCollectionViewTest.j

Content binding support.
Refactor indexes selection with modern code.
Rename an ivar.

CPCollectionView content binding & minor code refactor

---

AppKit/CPTextField.j

This PR implements : 
- cursor management via cursorUpdate instead of mouseMoved ;
- smart tracking area creation (only when needed) ;
- a fix to previous incorrect behavior when dragging on a disabled text field (previously, text was indeed selected).

Fixed: CPTextField doesn't optimize tracking areas management

---

Tools/XcodeCapp/XcodeCapp/Base.lproj/MainMenu.xib

Move **Preferences** menuItem up

Move XcodeCapp 'Preferences' menuItem to standard position

---

AppKit/CoreGraphics/CGContext.j
AppKit/CoreGraphics/CGContextText.j
Tests/Manual/CGCanvasContext/AppController.j

previously, drawing text on a view was next to impossible without using the dom.
this is fixed by this PR.
Code extracted from the core text branch.

fixed: CoreGraphics does not have basic text drawing support

---

Tools/XcodeCapp/XcodeCapp/XCCCappuccinoProjectController.m

Xcode 8 preview 6
SDK macos 10.12

FIXED: Fix a build error in XcodeCapp

---

AppKit/CPControl.j

Fixed:  typo in CPControl comment

---

AppKit/CPTableColumn.j
AppKit/CPTableHeaderView.j
AppKit/CPTableView.j
Tests/Manual/TableTest/DragAndDrop/AppController.j
Tests/Manual/TableTest/ViewBasedCib/AppController.j

Fixes #2530
@enquora can you test this please ?

FIXED: tableView:didDragTableColumn: was never sent

---

AppKit/CPCompatibility.j

CPSetPlatformFeature(aFeature, aBool)

NEW: CPCompatibility: add a function to set a feature externally.

---

AppKit/CPTableView.j

Fixes #2549 
@jasperdeb Can you confirm this works for you ?

CPTableView: fix invisible dragged rows

---

AppKit/CoreAnimation/CPAnimationContext.j
AppKit/CoreAnimation/CPViewAnimator.j
Tests/Manual/CPAnimatablePropertyContainerTest/AppController.j
Tests/Manual/CPAnimationContextTest/AppController.j
Tests/Manual/CPAnimationContextTest/Info.plist
Tests/Manual/CPAnimationContextTest/Jakefile
Tests/Manual/CPAnimationContextTest/index-debug.html
Tests/Manual/CPAnimationContextTest/index.html
Tests/Manual/CPAnimationContextTest/main.j
Tests/Manual/CPCollectionViewNibTest/AppController.j

Previously, the completionHandler of a context was not called if no animation was generated.
This could occur when the animator was not used at all, or the call to animator was not related to an animatable property,
or if the start and end values being the same, no css animation was needed.

FIXED: CPAnimationContext completionHandler was not called under certain circumstances.

---

Foundation/CPDateFormatter.j

Here is a pull request addressing my reported issue #2736

FIXED: CPDateFormatter not ready for german dates. Fixes #2736 

---

AppKit/CPCompatibility.j

Very naive Edge browser detection.
Could someone check for platform features and bugs ?

NEW: Edge browser detection

---

Tests/Manual/TrackingArea/AppController.j

There's no more -removeAllTrackingAreas.

FIXED: CPTrackingArea manual test was using removed method -removeAllTrackingAreas

---

Foundation/CPDateFormatter.j

Test: Tests/Foundation/CPDateFormatterTest.j

STYLE: refactoring using CPCharacterSet

---

bootstrap.sh

Existing --copy-local option to use local cappuccino-base has following limitations which are cumbersome when updating bootstrap process
* local source must be a zip archive - which requires an extra step after making changes to source
* local zip archive is erased after install - which makes repetitive testing more difficult
This commit intended to allow testing of updates to cappuccino-base narwhal-jsc.
With macOS 10.14 and later, narwhal-jsc must use modern c++ standard library.
libedit must do the same, so the dependency reference to it is updated to version which is current at this time.

Add --rsync-base option to bootstrap.sh

---

AppKit/CPWindow/CPWindow.j

fixed: wrong return type of isMiniaturized

---

AppKit/CPWindow/CPWindow.j

fixed: wrong return type in isMovable

---

AppKit/CPTextView/CPLayoutManager.j

fixed: wrong return type of backgroundColorForGlyphAtIndex:

---

AppKit/CPMenu/CPMenu.j

fixed: wrong return type of _menuWithName:

---

AppKit/CoreAnimation/CAAnimation.j

fixed: wrong return type in shouldArchiveValueForKey:

---

AppKit/Cib/_CPCibClassSwapper.j

fixed: wrong return type in initializer of _CPCibClassSwapper

---

AppKit/CPGraphicsContext.j

title says it all.
fixes #2817

fixed: typo in initWithGraphicsPort: declaration

---

AppKit/CPCursor.j

title says it all.
fixes: #2815

fixed: accidental creation of a global variable in CPCursor.j

---

AppKit/CPBrowser.j

subject says it all.
fixes #2625

fixed: CPBrowserDelegate_browser_imageValueForItem_ was defined twice

---

Foundation/CPProxy.j

fixed: wrong return type of forward::

---

AppKit/CPTableHeaderView.j

fixed: wrong return type of textField method in

---

AppKit/CPDocumentController.j

fixed: return type of openUntitledDocumentOfType:display:

---

Objective-J/Executable.js
Objective-J/FileExecutable.js

This pull request does not change anything except for when running in a none Narwhal environment.
This will be changed when Narwhal can be removed.

Fixed: Temporary fix so finding the compiler can work both in the Narwhal and Node world

---

AppKit/CPTextView/CPLayoutManager.j
AppKit/CPTextView/CPTextStorage.j

fixed: documentation for attributedStringWithAttachment: was missing

---

Tests/Foundation/CPAttributedStringTest.j

new: unittest for replaceOccurrencesOfString:withString:options:range:

---

AppKit/CPColor.j

This adds the CSS dictionaries to the description of the color.

NEW: This PR adds the CSS dictionaries to the description of a color (if this is a CSS based color)

---

AppKit/CPCheckBox.j

- Compatible with new button state management
This PR needs #2920 (CPButton).

Aristo3 : CPCheckBox (needs #2920)

---

AppKit/CPBox.j
Tools/nib2cib/NSBox.j

- modern Cocoa behavior
- new theme parameters

Aristo3: CPBox

---

AppKit/CPRadio.j

- Compatible with new button state management
This PR needs #2920

Aristo3: CPRadio (needs #2920)

---

AppKit/CPControl.j
AppKit/CPTextField.j
Tools/nib2cib/NSTextField.j

This PR : 
- replaces setTextFieldBackgroundColor by setBackgroundColor (as in modern Cocoa)

Aristo3: CPTextField

---

AppKit/CPWindow/CPWindow.j
AppKit/CPWindow/_CPWindowView.j

- CSS shadow
- new theme parameters

Aristo3: CPWindow

---

AppKit/CPStepper.j

This PR specifies correct / complete theme states for themed values `bezel-color-up-button` and `bezel-color-down-button`.

FIXED: This PR specifies correct / complete theme states for themed values

---

AppKit/CPMenu/CPMenu.j
AppKit/CPMenu/_CPMenuBarWindow.j
AppKit/CPMenu/_CPMenuManager.j
AppKit/CPMenu/_CPMenuWindow.j
AppKit/CPMenuItem/_CPMenuItemSeparatorView.j
AppKit/CPMenuItem/_CPMenuItemStandardView.j

- more theme parameters
- modern Cocoa behavior
- first menubar item can be displayed specifically
- all 3 control sizes are now managed
This PR needs #2919.

Aristo3: Menus (needs #2919)

---

AppKit/CPView.j

Adds the missing isCSSBased method.

Aristo3: This PR adds the missing -isCSSBased method to CPView

---

AppKit/CPPopUpButton.j

Adds a new theme parameter ```menu-offset``` instead of hard coded value.

NEW: This PR adds a new theme parameter "menu-offset" to CPPopUpButton instead of hard coded value

---

AppKit/CPSearchField.j
Tools/nib2cib/NSSearchField.j

- new theme parameters, including animation
- modern Cocoa behavior

Aristo3: CPSearchField

---

AppKit/CPButton.j

This PR :
- changes default bezel style to CPRoundRectBezelStyle
- removes unwanted comments

FIXED: default bezel style is now set to CPRoundRectBezelStyle

---

AppKit/CPScrollView.j
Tools/nib2cib/NSBox.j
Tools/nib2cib/NSTextField.j

This PR simply adds the needed missing declarations in order to get rid of 3 compilation warnings.

FIXED: This PR fixes 3 compilation warnings

---

AppKit/CPTabView.j
Tools/nib2cib/NSTabView.j

- modern Cocoa behavior
- new theme parameters
This PR needs #2924.

Aristo3: CPTabView (needs #2924)

---

AppKit/CPButton.j

fixed: CPButton's images were lost when becoming disabled

---

AppKit/CPSearchField.j

fixed: CPSearchField's bezel did not resize

---

Tools/capp/Resources/Templates/NibApplication/Jakefile
Tools/nib2cib/Converter.j
Tools/nib2cib/NSCustomResource.j

Support for space in path when running nib2cib

Node: Nib2cib space in path

---

README.markdown

make wording of system requirements more concise

Update README.markdown for system requirements

---

AppKit/CPView.j

FIXED: Before this PR, nib2cib failed if a color well or a scrollable text view was added in a CPBox

---

AppKit/CPMenuItem/CPMenuItem.j
AppKit/CPMenuItem/_CPMenuItemStandardView.j
AppKit/Cib/_CPCibCustomResource.j
Tools/nib2cib/NSCustomResource.j
Tools/nib2cib/NSMenuItem.j

Basic support for on/off/mixed state images for menuitems from the Interface Builder

Fixed: Basic support for on/off/mixed state images for menuitems from IB

---

Tools/Documentation/Cappuccino.doxygen
Tools/Documentation/preprocess/002.make_headers.sh

Changed glob pattern from _* to <empty> for the EXCLUDE_PATTERNS
configuration field in the doxygen configuration file.
This should fix #1956

Changed Cappuccino.doxygen EXCLUDE_PATTERNS to exclude nothing.

---

AppKit/CPView.j
AppKit/Cib/_CPCibCustomView.j

This is a (working) attempt to fix those issues.

FIXED: This PR adapts views and custom views decoding to fix "not ready view" bugs.

---

Foundation/CPString.j

fixed: CPString did not have containsString:

---

AppKit/CPView.j
AppKit/CPWindow/CPWindow.j

fixes: [#2177](https://github.com/cappuccino/cappuccino/issues/2177)

new: support for releasedWhenClosed in CPWindow

---

README.markdown

Prepare README.markdown for the upcoming release

---

AppKit/CPSegmentedControl.j

fixed: 1xp glitch with CPSegmentedControl in safari

---

AppKit/CPTextView/CPTextView.j

added documentation to the copy paste limitation

---

Tools/XcodeCapp/XcodeCapp/Base.lproj/MainMenu.xib

Remove hard-coded colours to allow dark mode support.

Set default project details view (no project selected) to default colours

---

AppKit/CPKeyValueBinding.j
Tests/AppKit/CPCheckBoxTest.j
Tests/AppKit/CPKeyValueBindingTest.j

fixes #1986 
@mrcarlberg what do you think?

New: give nil values the chance to be transformed to true via CPNegateBoolean

---

Foundation/CPSet/_CPConcreteMutableSet.j
Tests/Foundation/CPSetTest.j

new: for..of iteration for CPSet

---

AppKit/CPOutlineView.j

fixed: missing documentation of CPOutlineViewDataSource protocol

---

AppKit/CPViewController.j
Tests/AppKit/CPViewControllerTest.j

fixed: CPViewController doesn't participate fully in responder chain

---

AppKit/CPView.j
Tests/AppKit/CPViewTest.j

fixed: subview's window setting did not happen BEFORE _setSuperview

---

AppKit/CPCollectionView.j

fixed: CPCollectionview displayed an erroneous offset before the first row of content
