AppKit/_CPPopoverWindow.j
previously, the popover was positioned centered to the positioning view regardless of the given positioning rectangle.
this bug had been introduced by commit 8b29369 and all credits for the fix go to @Dogild
=> Fixed: -showRelativeToRect:ofView:preferredEdge is ignoring the positioning rectangle

Foundation/CPOperation.j, Foundation/CPOperationQueue.j, Tests/Foundation/CPOperationQueueTest.j, Tests/Foundation/CPOperationTest.j
... (CPOperation -start not called), when managed in a queue.
FIXED : After an operation started, either from a queue or explicitely, its finished property was never set to true.
This was causing dependant operation to never be executed.
After this commit, cancelled operations are started (but not executed) and correctly marked as finished.
Tests: CPOperationQueueTest and CPOperationTest for an operation managed by a queue or run explicitely.
=> FIXED : a CPOperation marked as cancelled was never started 

Foundation/CPDate.j
Previously, when making a CPDate with some constructors, we could pass a string or nil to create a date. For example it was allowed to do var date = [CPDate dateWithTimeIntervalSince1970:"10"];
Now this is not possible anymore and it works like in Cocoa, only number are authorized.
=> Fixed: constructor of CPDate can take string param

AppKit/CPCheckBox.j
Previously, the default size of a CPCheckBox created with the constructor method checkBoxWithTitle did not take in account the size of the checkBox view.
Now when calculating the size of the control, it will firstly calculate the size of the title and then add the size of the checkBox view and the offset.
Fixes #2281
=> Fixed: wrong default size of CPCheckBox when using constructor checkBoxWithTitle

Tools/XcodeCapp/XcodeCapp/AppController.m, Tools/XcodeCapp/XcodeCapp/UserDefaults.h, Tools/XcodeCapp/XcodeCapp/UserDefaults.m, Tools/XcodeCapp/XcodeCapp/XcodeCapp.m, Tools/XcodeCapp/XcodeCapp/en.lproj/MainMenu.xib
Previously, when xCodeCapp opened the errors & warnings panel, xcc was always the new active application of the system.
Now an option is available in the preferences of xcc to disable this possibility. If disable the errors & warnings panel will open itself, but your favorite text editor will still be the active application of your system (you will keep the focus).
=> New: option to active or not xCodeCapp when opening the errors & warnings panel

Foundation/CPURLConnection.j, Foundation/CPURLRequest.j, Objective-J/CFHTTPRequest.js, Tests/Foundation/CPURLConnectionTest.j, Tests/Foundation/CPURLRequestTest.j, Tests/Manual/CrossOriginTest/AppController.j, Tests/Manual/CrossOriginTest/Info.plist, Tests/Manual/CrossOriginTest/Jakefile, Tests/Manual/CrossOriginTest/README.md, Tests/Manual/CrossOriginTest/Resources/MainMenu.xib, Tests/Manual/CrossOriginTest/cors-server.py, Tests/Manual/CrossOriginTest/index-debug.html, Tests/Manual/CrossOriginTest/index.html, Tests/Manual/CrossOriginTest/main.j, Tests/Manual/CrossOriginTest/resp.json, Tests/Objective-J/CFHTTPRequestTest.j
This Pull Request deals with three inter-related issues.
1. The presence of `withCredentials` on CPURLConnection required that the connection be initialized with credentials or not. This commit moves `withCredentials` to CPURLRequest, where it can be set prior to initializing the connection. This setting will then get picked up and transferred to the underlying CFHTTPRequest as needed. This also simplifies the implementation of `withCredentials` in Capp.
2. CPURLConnection was missing the `originalRequest` and `currentRequest` methods, present in Cocoa since 10.8. These were added.
3. CPURLRequests were not able to be deep copied using the `copy` method (provided by CPCopying). The CPCopying protocol was added to CPURLRequest to implement the copy method allowing CPURLRequest objects to …
=> Rework of withCredentials, CPURLRequest, and CPURLConnection

AppKit/Themes/BlendKit/BKShowcaseController.j
Previously the showcase of the themes were broken. This was due to a change of the CPCollectionView, previously we used to use the delegate collectionViewDidChange. This delegate method has been removed. We now use an observer on the selectionIndexes.
=> Fixed: showcase of themes are broken

AppKit/CPView.j, AppKit/Platform/DOM/CPDOMDisplayServer.h
Previously the method `CPDOMDisplayServerSetStyleBackgroundSize` was named `CPDomDisplayServerSetStyleBackgroundSize`, which was inconsistent with the names of all other similar methods in the CPDOMDisplayServer.h file. This commit fixes this and updates all instances of its use in CPView.j.
=> Fixed: Inconsistent naming of CPDOMDisplayServerSetStyleBackgroundSize

AppKit/CPDatePicker/_CPDatePickerCalendar.j
Previously, CPDatePicker did not disable the dates outside of minDate and maxDate. This left the user wondering why some dates are not clickable for no apparent reason.
This PR sets the state to disabled if the tile not within minDate and maxDate.
Fixes #2262
=> Fixed: CPDatePicker does not grey out dates outside of minDate and maxDate

Tests/AppKit/CPStepperTest.j, Tests/Foundation/CPIndexSetTest.j, Tests/Foundation/CPMutableArrayTest.j, Tests/Foundation/CPTimeZoneTest.j
Previously, some unit-tests had the same name in a test file. Now they have unique name.
=> Fixed: Duplicate unit-tests

AppKit/Themes/Aristo2/ThemeDescriptors.j
Now it is white. The text-color values match the CPTextField values for the same theme states.
TEST: Tests/Manual/CPTableViewLion/
=> FIXED: The text color of a checkbox inside a selected table row was black

AppKit/CPObjectController.j
`CPObjectController>>setValue:forKey:` used the `theKeyPath` parameter as keypath **and** value.
=> Fixed: Wrong value parameter in CPObjectController>>setValue:forKey:

AppKit/CPDatePicker/CPDatePicker.j
Previously, the CPDatePicker could get an invalid javascript date.
Now it will raise an exception when getting an invalidate date.
=> Fixed: The CPDatePicker can take invalid date

AppKit/CPSegmentedControl.j
Previously, when clicking on segment, the divider did not have the expected color. Now they does.
=> Fixed: CPSegmentedControl divider wrong color

AppKit/_CPPopoverWindow.j
Previously, when the frame of a superview of the targetedView would update, the popover did not update its position.
Now it does by observing each frame of each superviews of the targetedView.
=> Fixed: CPPopover position does not update each time

AppKit/CPTableHeaderView.j, Tools/nib2cib/NSTableHeaderView.j
Previously, there was a warning when compiling the file  NSTableHeaderView.j
=> Fixed: compilation warning for NSTableHeaderView.j

Foundation/_CPCollectionKVCOperators.j, Tests/Foundation/CPKVCArrayTest.j, Tests/Foundation/CPSetTest.j
This PR adds the KVC operators unionOfObjects, distinctUnionOfObjects, unionOfArrays, distinctUnionOfArrays, distinctUnionOfSets for array and set.
Unit-Tests Tests/Foundation/CPKVCArrayTest.j
Unit-Tests Tests/Foundation/CPSetTest.j
=> New: added KVC operators unionOfObjects, distinctUnionOfObjects, unionOfArrays, distinctUnionOfArrays, distinctUnionOfSets

AppKit/CPView.j, Tests/AppKit/CPViewTest.j
This PR adds the possibility to layout or not a CPView.
Previously, once setNeedsLayout was called on a CPView, it wasn't possible to cancel the layout of the view.
Now we can as in cocoa. The method setNeedsLayout will still work (it calls the method setNeedsLayout: with YES).
UnitTests in Tests/AppKit/CPViewTest.j
=> New: added the method setNeedsLayout:

AppKit/CPTableColumn.j, Tests/AppKit/CPTableViewTest.j
Before this fix, the CPTableColumn binder was not correctly reloading
the table when the number of rows changed. Now we reload fully the
dataviews when the number of rows changes. If no rows are
inserted/deleted, there is an optimization: we just need to reload the
objectValues and leave the dataviews untouched.
With Test in Tests/AppKitCPTableViewTest.j
Fixes #2317
=> FIXED: Exception when rows were removed in a table with binded columns.

AppKit/CPTableView.j, Tests/AppKit/CPTableViewTest.j
This PR adds the method viewAtColumn:row:makeIfNecessary: in CPTableView.
This method first attempts to return an available view, which is generally in the visible area. If there is no available view, and makeIfNecessary is YES, a prepared temporary view is returned. If makeIfNecessary is NO, and the view is not available, nil will be returned.
An exception will be thrown if row is an invalid row index and if column is an invalid column index.
The returned result should generally not be held onto for longer than the current run loop cycle. Instead they should re-query the table view for the row view.
UnitTests in Tests/AppKit/CPTableViewTests.j
=> New: Added method viewAtColumn:row:makeIfNecessary: in CPTableView

AppKit/CPTokenField.j
Previously, the CPApplication dispatched the current event when having the auto complete menu of a CPTokenField opened.
This occurs weird behavior. For instance when hitting enter on the menu and having a default button, the action of the button was triggered.
Now, the CPTokenField handles the key enter when the autocomplete menu is opened.
=> Fixed: CPApplication dispatch the event when having the auto complete menu of a CPTokenField opened

Foundation/CPCache.j, Foundation/Foundation.j, Tests/Foundation/CPCacheItemTest.j, Tests/Foundation/CPCacheTest.j
This is an implementation of NSCache https://developer.apple.com/library/mac/documentation/Cocoa/Reference/NSCache_Class/index.html
I tried to reproduct the default behaviour, but I had to give up the implementation of NSDiscardableContent, because Cappuccino don't provide a mechanism to count objects usage, so the property evictsObjectsWithDiscardedContent also disappear from my implementation.
=> New: added the CPCache class

AppKit/CPTableColumn.j
This PR updates the documentation to clarify that bindings work only after a column has been added to a tableview.
fixes issue #1686
=> Clarification for CPTableColumn's binding documentation

AppKit/CPColorPanel.j, AppKit/CPMenu/_CPMenuBarWindow.j, AppKit/CPRuleEditor/_CPRuleEditorViewSlice.j, AppKit/CPWindow/_CPHUDWindowView.j, AppKit/CPWindow/_CPStandardWindowView.j, AppKit/Cib/CPCibHelpConnector.j, AppKit/_CPPopoverWindow.j, Objective-J/ObjJAcornCompiler.js, Tests/Manual/CompilationTests/TestCases/11.j, Tests/Manual/CompilationTests/TestCases/7.j, Tests/Manual/CompilationTests/run.py, Tools/nib2cib/NSButton.j, Tools/nib2cib/NSDatePicker.j
Today you can declare a duplicate ivar in a subclass. Now the compiler will generate an error.
This fixes #2271 and #362
=> Duplicate ivar on superclass

AppKit/CPTableView.j, Tests/AppKit/CPTableViewReloadDataTest.j, Tests/AppKit/CPTableViewTableColumnTest.j, Tests/AppKit/CPTableViewTest.j
Previously, when reloading a CPTableView the run loop was explicitly call to layout the tableView. This is not the case in Cocoa.
You can call several times the method reloadData and this will only lay out the tableView one time.
=> Fixed: reloadData in CPTableView run the runLoop

AppKit/CPSegmentedControl.j, Tests/AppKit/CPSegmentedControlTest.j
previously, -setSelectedSegment:-1 was not visually deselecting the
segments and selectedSegment was not set to -1.
With tests.
=> FIXED: CPSegmentedControl -setSelectedSegment:-1

Foundation/CPArray/_CPArray.j
The implementation of CPArray's hash method deliberately differs from cocoa.
This PR adds the appropriate documentation.
Fixes issue #10
=> Added documentation for CPArray's hash method

AppKit/CPDatePicker/CPDatePicker.j, AppKit/CPDatePicker/_CPDatePickerClock.j, AppKit/CPDatePicker/_CPDatePickerTextField.j
CPDatePicker was setting american date/time format for GB locale as it was checking against the locale language.
I have removed not needed _isEnglishFormat method and replaced it with _isAmericanFormat.
Now for US locale format stays as it should (mm/dd/yyyy 12h clock with AM/PM)
and for GB locale format is in EU standard (dd/mm/yyyy 24h clock)
=> FIXED CPDatePicker AM/PM time format for GB locale

AppKit/Jakefile, CommonJS/bin/press, CommonJS/lib/cappuccino/fontinfo.j, CommonJS/lib/cappuccino/imagesize.j, Jakefile, Objective-J/CFHTTPRequest.js, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/CommonJS/lib/objective-j/jake.js, Objective-J/Jakefile, Tools/XcodeCapp/Jakefile, Tools/nib2cib/Converter.j, Tools/nib2cib/main.j, common.jake
Previously, when popen was called, the 3 streams (stdin, stderr and stdourt) where never closed. This was the reason of the having an impossible number of open files.
This patch ensure all streams are closed after using them. This means that the ulimit trick is no more necessary
=> FIXED: Closes all streams after a OS.popen()

AppKit/CPClipView.j, Tests/AppKit/CPScrollViewTest.j
Previously, the method documentVisibleRect did not return the expected result. An issue happened when using this method on a scaled view. The converted rect was converted in the wrong context.
Unit test in Tests/AppKit/CPScrollViewTest.j
Fixed #2356
=> Fixed: documentVisibleRect in CPScrollView does not return the expected result

Tools/nib2cib/NSFont.j
This patch adds support for the new way of defining the default font from Xcode 7 beta. The patch also supports the old explicit 'Lucida Grande' of previous version.
=> FIXED: Fonts from IB not correctly interpreted in OSX El Capitain

Foundation/CPURLConnection.j, Foundation/CPURLRequest.j, Objective-J/CFHTTPRequest.js
This PR adds the possibility to set the timeout and the cache policy of a CPURLRequest.
For that, there are new things in the framework :
- CFHTTPRequest has now the functions setTimeout(), getTimeout() and isTimeoutRequest
- CPURLRequest has now the methods +requestWithURL:cachePolicy:timeoutInterval: and -initWithURL:cachePolicy:timeoutInterval:
- CPURLConnection does not call the delegate didReceiveData: when a request has timed out. I will call the delegate didFailWithError:
- Cache is now possible for a CPURLRequest, only CPURLRequestReturnCacheDataElseLoad, CPURLRequestReturnCacheDataDontLoad and CPURLRequestReloadIgnoringLocalCacheData are supported. By default CPURLRequestReloadIgnoringLocalCacheData.
- Default timeout has been set to 60sec as in cocoa.
- A request is considered …
=> New: added timeout and cache feature in CPURLRequest

Foundation/CPPredicate/_CPPredicate.j, Tests/Foundation/CPPredicateTest.j
When parsing a predicate format that contains a constant boolean expression
(e.g., 'key = YES') the value of the returned constant value expression has
the wrong type. Instead of using native types as values, the parser uses
[CPNumber +numberWithBool:].
This commit changes the format parser (CPPredicateScanner) to use native
booleans for constant value expression.
There's a test case that checks the parse result and an additional test
that ensures boolean expressions evaluate as expected with different kinds
of objects. The latter test passed before the fix but was added to ensure
compliance with Cocoa.
=> Fixed: preserve type of boolean values when parsing CPPredicate format

AppKit/CPTextField.j, AppKit/CPView.j
Previously, when making a right click and when a cappuccino menu was not displayed, the system menu was displayed. Now we don't display this menu anymore as in cocoa. We only display when making a right click on a CPTextField.
=> New: default menu system is now disable for every right click except for the CPTextField

AppKit/CPView.j, AppKit/CPVisualEffectView.j, Tests/AppKit/CPViewTest.j
Previously, when using a viewBased CPTableView Cappuccino just crashed.
This was due to the new appearance feature. Indeed, at the end of the method initWithCoder: of CPView, we set the appearance of the current view and the themeStates of the view and its subviews. For an unknown reason some of these subviews were not completely initialized (see comment line 3742), this made crashed cappuccino because _themeState was null.
To fix this issue, we send the method setAppearance when the current stack was performed. (Magic setTimeout...).
This is for sure not the ultimate best fix, but it's prevent to have a broken master. We will need in the future to fix this issue in a better way.
=> Fixed: crash when using a viewBased CPTableView with appearance

Foundation/CPArray/_CPJavaScriptArray.j, Tests/Foundation/CPArrayTest.j, Tests/Foundation/CPMutableArrayTest.j
The init method ’initWithObjects:count:’ for CPArray did not work on native CPJavaScriptArray when ’count’ is not the same as the length on the provided array.
A test case for this is also added in the test class CPArrayTest
=> Fixed: The init method ’initWithObjects:count:’ for CPArray did not work

Foundation/CPDictionary.j, Tests/Foundation/CPDateFormatterTest.j, Tests/Foundation/CPDictionaryTest.j, Tests/Foundation/CPTimeZoneTest.j
CPDictionary initWithObjectsAndKeys: was not compliant with Cocoa or the init method ’initWithObjects:forKeys:’ when duplicated keys was passed to the method.
Test cases are also added
=> CPDictionary handles duplicate keys in correct way on init

AppKit/AppKit.j, AppKit/CPColor.j, AppKit/CPTheme.j, AppKit/CPView.j, AppKit/Themes/Aristo/ThemeDescriptors.j, AppKit/Themes/Aristo2/ThemeDescriptors.j, AppKit/Themes/BlendKit/BKThemeDescriptor.j, AppKit/Themes/CommonJS/blendtask.j, AppKit/_CPObject+Theme.j
The purpose of this feature is to create theme for every object of the AppKit. Previously, we could not theme object like CPColor, however CPColor could be very interesting to theme, value like alternateSelectedControlColor were hard coded in the framework. With this PR, we can now theme a CPColor and take some values from the current theme of the application. Then, this PR offers the possibility to refactor the themeDescriptors, some classes contains theme attributes for other class (CPTabView and  CPTabViewItem for instance).
How doe it work ? A new category _CPObject+Theme.j has been added to the AppKit. This category contains every theme methods needed to theme an object (previously this category was in CPView). We add utils method like _encodeThemeObjectsWithCoder: and …
=> New: possibility to create a theme for every object of the Appkit

AppKit/CPAlert.j, AppKit/CPApplication.j, AppKit/CPDocument.j, AppKit/CPDocumentController.j, AppKit/CPOutlineView.j, AppKit/CPTableView.j, AppKit/CPWindow/CPWindow.j, Foundation/CPKeyValueObserving.j, Tools/nib2cib/NSClassSwapper.j
In some places the objj_msgSend function is called directly. Most of the times the old slower version is called. This commit will use the never faster version instead.
=> Use the faster objj_msgSend instead of the old slower objj_msgSend

Foundation/CPNotificationQueue.j, Foundation/Foundation.j, Tests/Foundation/CPNotificationQueueTest.j
Cappuccino provides a framework for sending messages between objects within
a process called notifications. CPNotificationQueue objects (or simply notification queues)
act as buffers for notification centers (instances of CPNotificationCenter).
Whereas a notification center distributes notifications when posted,
notifications placed into the queue can be delayed until the end of the current pass through the run loop
or until the run loop is idle. Duplicate notifications can also be coalesced so that only one notification
is sent although multiple notifications are posted. A notification queue maintains notifications
(instances of C¨Notification) generally in a first in first out (FIFO) order.
When a notification rises to the front of the queue, the queue posts it to the notification …
=> New: added the class CPNotificationQueue

AppKit/CPComboBox.j, AppKit/CPTextField.j, AppKit/CPTokenField.j, Foundation/CPRunLoop.j, Tests/Foundation/CPRunLoopTest.j
Previously, we could only give a selector and a target for perform in the runLoop. Now we can give a block.
This feature is used in the CPTextField class. Previously, when we wanted to call a function at the end of the stack we used window.setTimeout, however due to HTML5 specifications this wasn't called just at the end of the stack but at least 4ms (more information here https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/setTimeout#Minimum_delay_and_timeout_nesting). Now we give a block to perform, and this block will be performed in the next runloop.
Unittest has been added in Tests/Foundation/CPRunLoopTest.j
=> New: added the method performBlock in CPRunLoop

AppKit/Jakefile, AppKit/Themes/BlendKit/Jakefile, Foundation/Jakefile, Jakefile, Objective-J/Bootstrap.js, Objective-J/CFHTTPRequest.js, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/CommonJS/lib/objective-j/jake/bundletask.js, Objective-J/FileExecutable.js, Objective-J/ObjJAcornCompiler.js, Objective-J/Runtime.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/colon-selector-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/complex-receiver-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/keyword-in-selector-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/multiple-parameters-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/no-parameters-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/one-parameter-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/self-as-receiver-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/ternary-operator-argument-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Misc/parenthesis-return-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/OutputTest.j, Tools/capp/Resources/Templates/Application/Jakefile, Tools/capp/Resources/Templates/Application/index-debug.html, Tools/capp/Resources/Templates/Framework/Jakefile, Tools/capp/Resources/Templates/NibApplication/Jakefile, Tools/capp/Resources/Templates/NibApplication/index-debug.html, Tools/capp/Resources/Templates/ThemeDescriptor/index-debug.html, common.jake
This pull request will make Objective-J run faster by implementing a more efficient ```objj_msgSend``` function and ```objj_method``` implementation. The compiler can also optionally inline the function to increase the speed even more.
Initial tests show that the speed increase is more than 50% in special cases. For a general Objective-J application the speed increase is around 20%.
1. More efficient ```objj_method``` implemention. That bad thing here is that the ```name``` property on ```objj_method``` has to change to ```method_name```.
2. ```objj_msgSend``` and ```objj_msgSendSuper``` functions has a more efficient implementation.
3. Array and Dictionary Literals generate more efficient code.
4. The ```objj_msgSend``` and ```objj_msgSendSuper``` functions are optionally inlined by the …
=> Speedup of the Cappuccino framework by more efficient objj_msgSend

AppKit/CPButton.j, AppKit/CPButtonBar.j, AppKit/CPDatePicker/_CPDatePickerCalendar.j, AppKit/CPStepper.j, AppKit/CPTableHeaderView.j, AppKit/CPTableView.j, AppKit/CPTheme.j, AppKit/CPTokenField.j, AppKit/CPView.j, AppKit/Themes/Aristo2/ThemeDescriptors.j, AppKit/Themes/BlendKit/BKThemeDescriptor.j, AppKit/_CPAutocompleteMenu.j, AppKit/_CPObject+Theme.j, Tests/AppKit/CPThemeTest.j, Tests/AppKit/CPViewTest.j
Theme attributes are created for every attribute on every themeable object (mostly views). In a large application there will be many of them. In our project we have over 100,000 theme attributes created if all cib file are loaded.
This pull request will cache these in a better way than before. Fewer will be created and we get better performance. Before in Safari 9.0 I could load a large cib file in 1.25 seconds. Now it loads in 1.05 seconds. Similar speed gains in Chrome and Firefox.
This is done by making ```_CPThemeAttribute``` immutable and cache it in a better way.
This pull request is built on #2386 that will also give a nice speed increase.
=> Faster theme attribute handling

AppKit/CPButton.j, AppKit/CPTableHeaderView.j, AppKit/CPTableView.j, AppKit/CPTheme.j, AppKit/CPTokenField.j, AppKit/Themes/Aristo2/ThemeDescriptors.j, AppKit/_CPObject+Theme.j, Tests/AppKit/CPViewTest.j
ThemeState was changed from a bit mask to a Javascript object last year. This was done to handle more states as a bit mask is limited to 32 bits.
The performance impact of this was not good and made theme handling slower.
This pull request adds a cache mechanism to get back some of the lost performance.
Also fixed some other small performance improvements.
I tested to load a large cib file in Safari 9.0 and it took 1.80 seconds. With this change it will load in 1.60 seconds. Similar speed gains in Chrome too.
=> Faster theme state handling

AppKit/CPTabView.j
With the lately merged PR #2339 it breaks the default CPTabView item selection. The item is correctly selected inside the internal state of the object but the tab view is not loaded at all.
This is due to the fact that the _selectedTabViewItem contains the selected item from the init call and the selectTabViewItemAtIndex: method is called within the awakeFromCib method to load the selected tab, which fails as this happens to be already selected.
This PR fixes that.
=> Fixed: default selection of a CPTabView item

Objective-J/Debug.js, Objective-J/Runtime.js, Tests/Objective-J/Preprocessor/BehaviorTests/MethodTest.j
Added runtime functions to get return type and parameter types on methods.
The old function ```method_getTypes```was not compliant to how Objective-C runtime works. This function is now deprecated.
=> Objective-J runtime method type accessor functions

Foundation/CPKeyValueObserving.j, Objective-J/CommonJS/lib/objective-j.js, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/ObjJAcornCompiler.js, Tests/Foundation/CPKeyValueObservingTest.j, Tests/Objective-J/Preprocessor/OutputTests/Class/accessors.js, Tests/Objective-J/Preprocessor/OutputTests/Class/root-class-multiple-ivars.js, Tests/Objective-J/Preprocessor/OutputTests/Class/root-class-one-ivar.js, Tests/Objective-J/Preprocessor/OutputTests/Misc/ref-self.js, Tests/Objective-J/Preprocessor/OutputTests/OutputTest.j, Tools/capp/Resources/Templates/Application/index-debug.html, Tools/capp/Resources/Templates/Application/index.html, Tools/capp/Resources/Templates/NibApplication/index-debug.html, Tools/capp/Resources/Templates/NibApplication/index.html, Tools/capp/Resources/Templates/ThemeDescriptor/index-debug.html, Tools/capp/Resources/Templates/ThemeDescriptor/index.html
This will make sure method and ivar type information is provided to the Objective-J runtime for all types of builds. It is done by providing the Objective-J compiler with option ```IncludeTypeSignatures```. It can optionally be turned off.
This will fix: #2398
A fix is also included that make sure that type signatures are copied to KVO method implementation for a object that is observed with KVO.
Some test cases are added for this.
=> Default include type signatures for all kind of builds

Foundation/CPPredicate/_CPSubqueryExpression.j, Tests/Foundation/CPPredicateTest.j
When the predicate part of a subquery expression was containing
variables, the substitution was ignored.
Now, the subpredicate can contain variables that will be substituted
when calling evaluateWithObject:substitutionVariables:.
Added expression test and predicate parsing test.
=> FIXED: Subquery expressions were ignoring evaluation context

AppKit/CPBox.j, Tools/nib2cib/NSBox.j
Previously, when having a CPTableView in a CPBox, nib2cib failed due to a superview not defined yet. This was raised because in nib2cib we used the method setFrame on the CPBox to modify the frame of the CPBox (we need to modify this frame because the sizing difference between cappuccino and cocoa). We now directly modify the attribute _frame from the object and update the bounds in the same time.
This PR fixed another bug as well. Previously the contentView of the CPBox was not encoded, we now encode it. This allows us to get a full CPView object for the contentView, previously we got a weird (I have no idea how this object was created though...) object CPView with some missing attributes. This raised a crash because _trackingAreas or _themeState were not defined in this object.
Fixed …
=> Fixed: nib2cib on a NSBox fails when having a CPTableView in it

Tools/XcodeCapp/XcodeCapp/SettingsView.xib
The horizontal margin was larger than the vertical margin, and larger than the margin guideline for Cocoa.
Also one of the hint text lines was much closer to its textbox than the other two, and not well aligned within its textfield (should be right aligned).
=> Fix some typos/grammar in XcodeCapp settings, plus improve layout.

Foundation/CPArray/_CPArray.j, Foundation/CPArray/_CPJavaScriptArray.j, Tests/Foundation/CPArrayTest.j
This new method maps the receiver using the provided function.
Similar to javascript or swift map function.
There are tens of places in the fmw where using this method can reduce the amount of code.
With test.
=> New: CPArray -arrayByApplyingBlock:

Objective-J/Jakefile
Can now build Cappuccino in directory with space in the path
=> Fixed: Allow build in directory with space in path

Foundation/CPKeyedUnarchiver.j
If parsing of a plist is invalid it will return nil instead of throwing an 'undefined is not an object' exception
=> Does not throw exception if plist is not valid. It will return nil instead

AppKit/CPObjectController.j, Tools/nib2cib/NSObjectController.j
This pull request reads more attributes from the xib/cib file. The attributes are entity name and uses lazy fetching.
=> Allow CPObjectController to get more attributes from the xib/cib file.

Foundation/CPNumber.j, Foundation/CPString.j, Tests/Foundation/CPNumberTest.j, Tests/Foundation/CPStringTest.j
This makes the classes more compliant to Cocoa
=> Fixed: Added ’integerValue’ method for CPNumber and CPString.

Objective-J/Executable.js
We have not changed it for support of older browsers.
Chrome version 51 and above writes a warning about it
in the console so it is time now.
=> Fixed: //@ sourceURL=... is deprecated since many years ago.

AppKit/CPTableHeaderView.j
Previously, when having a CPTableViewHeader without a CPTableView, cappuccino just crashed.
We now check if _tableView is set before iterating on the tableview's columns.
=> Fixed: crash when having a CPTableViewHeader without a CPTableView

AppKit/CPCompatibility.j
Fix for issue: https://github.com/cappuccino/cappuccino/issues/2365
=> FIXED: Cursor key binding methods do not fire in IE11 #2365

AppKit/CPObjectController.j
When setting entity name from code the ```_managedProxy``` will be null and the name will not be stored
=> Fixed: Setting entity name from code does not work

AppKit/CoreAnimation/CPAnimationContext.j
getPropertyCSSValue have been deprecated in chrome and possibly other engines. Replacing with getPropertyValue supported by all browsers.
=> FIXED: in CPAnimationContext, 'Unknown function getPropertyCSSValue' error in chrome

Foundation/CPKeyValueObserving.j, Tests/Foundation/CPKeyValueObservingTest.j
Only the first added observer will observe the attribute for the relationship object on a dependent relationship keypath. This PR fixes that problem.
Also, an optimisation on when the willChange… chain is running, there is no need to replace the observers as no new values are set yet. That will be done when the didChange… chain is running.
Test case is provided
=> Dependent key paths use a relationship

AppKit/CPRuleEditor/CPPredicateEditorRowTemplate.j
CPPredicateEditorRowTemplate has been modified to allow a correct comparision of date objects when using the CPDateAttributeType
Before this correction, the predicate format was using a string representation of a date instead of a date object.
=> Fixed: date comparisons in CPPredicateEditor

AppKit/CPTableHeaderView.j
previously, autoscrolling was turned off when dragging a tableview column.
this PR activates autoscrolling that had been deliberately blocked in the past.
you can verify that autoscrolling during column-dragging works in manual test TableTest/ColumnResize
(make the browser window narrow enough)
fixes #2421
=> enable autoscrolling for tableview columns

AppKit/CPColorWell.j
When using a CPColorWell on a platform window other than the main platform window, the CPColorPanel was always opened on the main platform window.
This PR forces the CPColorWell to set the platform window of the CPColorPanel to its own platform window.
fixes #2387
=> Fixed: CPColorPanel always opens in main platform window.

AppKit/Platform/CPPlatformWindow.j, AppKit/Platform/DOM/CPPlatformWindow+DOM.j
While dragging a window or a custom view, if the user also pushes on the right mouse button (by mistake), the drag operation is stopped (without any notification to the application).
This PR modifies the DOM event processing so that the behavior is now compatible with the Cocoa way.
fixes #2378
=> Fixed: right mouse clic during a drag operation cancels it

AppKit/CPView.j, Tests/AppKit/CPViewTest.j
Also Fixed: when a view is hidden by a hidden superview and added to a non
hidden superview, the -viewDidUnhide message is sent.
With test : CPViewTest.j
=> FIXED: CPView received multiple -viewDidHide/Unhide messages

AppKit/CPColorPicker.j
Previously, the background of the brightness slider had a uniform color.
This was because the size of the colorWithPatternImage: had not been initialized.
With this PR, there is a nice gradient from black to the selected color like in cocoa.
=> Fixed: brightness_bar.png was not displayed in CPColorPicker

Objective-J/Bootstrap.js, Objective-J/CFHTTPRequest.js, Objective-J/CommonJS/lib/objective-j.js, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/CommonJS/lib/objective-j/jake/bundletask.js, Objective-J/Executable.js, Objective-J/FileExecutable.js, Objective-J/ObjJAcornCompiler.js, Objective-J/acorn.js, Objective-J/acornwalk.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/super-selector-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/super-selector.j, Tests/Objective-J/Preprocessor/OutputTests/Messages/super-selector.js, Tests/Objective-J/Preprocessor/OutputTests/OutputTest.j, Tests/Tools/ToolsTest.j
The life will be easier to have the same in both environments.
Warnings and errors now don’t use read only properties for line and column information. So the test cases in Toolstest.j now work in modern JS engines.
It is also easier to set options for the compiler.
=> Fixed: Merged in the parser and compiler that is used in the node objj-runtime

AppKit/CPPasteboard.j
previously, CPPasteboad contained dead code that was left over from refactoring the native pasteboard stuff into the DOM folder
=> CPPasteboad.j removal of dead code

AppKit/Platform/DOM/CPPlatformWindow+DOM.j
Previously, the scrolling events were generated in a setTimeout with a delay of 0ms.
These were not reliably executed in recent chrome versions which caused freezes during scrolling with momentum on older systems such as a MBP late 2011.
This PR replaces the setTimeout with requestAnimationFrame and uncomments the limitDateForMode:CPDefaultRunLoopMode to enforce the visual updates.
Tested on FF, Safari and of course chrome.
Fixes #2468
=> fixed: scrolling events are missed on slower maschines in chrome 52

AppKit/Platform/DOM/CPPlatformPasteboard.j
previously, every native nativePasteEvent: compared the pasted content to [pasteboard _stateUID], which is always undefined in the current implementation of CPPasteboard. This resulted in a call to pasteboard declareTypes:[CPStringPboardType] owner:self, effectively removing all other representations during each paste.
This PR makes capp to only call [CPStringPboardType] owner:self if the system and capp CPStringPboardType actually differ. This makes the system and capp pasteboards cooperate. This is a prerequisite for proper copy/paste support of the new text system.
Fixes #2062 and
https://github.com/daboe01/CPTextView/issues/109
=> fixed: cappuccino pasteboad is always clobbered by system pasteboard

AppKit/CPView.j
Previously CPView used "==" as an equality checker. This commit changes these to use "===" for consistency.
=> Formatting: CPView

Tools/nib2cib/NSIBObjectData.j, Tools/nib2cib/NSNibConnector.j
ibtool optionally generates warnings in the nib file that are wrapped into a connection. Now we print the warning when nib2cibing but ignore this entry when converting to cib.
=> nib2cib: discard warnings in the nib file.

AppKit/CPTabView.j, Tests/AppKit/CPTabViewTest.j
Before this commit, a tab view could have an empty selection with the
following circumstances:
- The tab view was not created in IB
- the Tab View selection had not binding management
With test.
=> Fixed: CPTabView should not allow empty selection

Foundation/CPObject.j, Tests/Foundation/CPObjectTest.j
Tests if instances of given class implement a selector.
With test.
The naming is from cocoa where this method is semi-public, id est not documented but not underscored.
A possible usage is to compute in CPView the _viewFlags (custom layout & drawing) at the class level instead of the instance level and make them more accessible from outside.
=> New: CPObject -instancesImplementSelector:(SEL)aSelector

AppKit/CPSegmentedControl.j, AppKit/_CPImageAndTextView.j
A private flag have been added in _CPImageAndTextView. It must be set
to YES when it does not make sense for a control to hold multiline text.
This is now the case for all CPSegmentedControl.
Test: In CPSegmentedControlTest, hit « Add Segment with flexible
width » button. The new label should be vertically centered.
=> New: Allow a text based control to stay on a single line when text wraps.

AppKit/CPTextView/CPTextView.j, AppKit/CPTextView/_CPRTFParser.j, Foundation/CPDate.j, Foundation/CPDateFormatter.j, Foundation/CPDecimal.j, Foundation/_CPCollectionKVCOperators.j, Tools/nib2cib/Converter.j
On linux distributions with gcc > 4.9 cappuccino does not build because of the format of the RegEx.
I replaced all RegEx by a construct like new RegExp("xxx")
In the RegEx itself the \ had to be escaped for this to work.
This Pull Request refers to this [issue](https://github.com/cappuccino/cappuccino/issues/2499)
=> Fix RegEx for gcc > 4.9

AppKit/CPTheme.j
This line of code was introduced years ago with a variable that
javascript is happy to add to the global name space.  Clearly it
was meant as a local variable.  Probably a cut and paste error
because other places in the code use the same syntax but there the
value is a local because the var statement for it appeared elsewhere
in the function.
Once code like this is cleaned up to use the new 'let' construct,
as well as 'use strict', mistakes like this will be much less likely
to go uncaught.
=> Make variable local: key

Objective-J/Runtime.js
A long standing bug that never mattered because each class is
initialized with a protocol_list set to an empty array.  This
is not the case for the protocol objects but there the syntax
was correct already.
=> Fix aClass.protocol_list syntax

Objective-J/Executable.js
It is polluting the global namespace.
Seven years ago this line was added and even then the variable wasn't
being used but it was a local variable so would have been hard to spot
unless a linter should catch things like that.
Then some four years ago it was accidently converted to a global
variable because the line above it ended in a semicolon rather than
a comma.  'use strict' didn't exist at the time this file was created
and hasn't been added in general yet.
=> Removed an unused variable: cachedSearchResults.

Objective-J/Runtime.js
From the first day this class was added to the repo, the sub_classes
property, which is initialized with an empty array, has gone unused.
Removing it.  A little less code.  A little subsequent processing
and memory used.
=> Remove objj_class.sub_classes property

AppKit/CPSplitView.j, Tests/Manual/CPSplitViewTest/AppController.j
Perf: Exit a loop when the current divider is found.
Fixed: Do not start tracking when the mouse is not over a divider (see mouseDown:)
Fixed: Properly catch single-click, double-click, dragging on a divider.
Previously, 
• a double-click was also catched as a single-click on mouse up,
• dragging was handled in mouse down before tracking actually begins.
Manual test: All split views can be collapsed when double-clicking the first divider.
=> CPSplitView -trackDivider: performance

AppKit/Jakefile, Foundation/Jakefile, Objective-J/CFBundle.js, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/Executable.js, Objective-J/FileExecutable.js, Objective-J/Includes.js, Objective-J/ObjJAcornCompiler.js, Objective-J/acorn.js, Objective-J/source-map.js, Tools/capp/Resources/Templates/Application/Jakefile, Tools/capp/Resources/Templates/Application/index-debug.html, Tools/capp/Resources/Templates/Application/index.html, Tools/capp/Resources/Templates/Framework/Jakefile, Tools/capp/Resources/Templates/NibApplication/Jakefile, Tools/capp/Resources/Templates/NibApplication/index-debug.html, Tools/capp/Resources/Templates/NibApplication/index.html
We can now debug and step inside the Objective-J source file thanks to new support for source maps.
The Cappuccino framework will now compile with source maps for the debug version. The Release version is not changed.
To turn this option on for your project add the ```-S``` flag in your Jakefile. Search for the ```setCompilerFlags``` function to find where the compiler options are set.
In the Browser you need to add ```SourceMap``` as compiler option to your index-debug.html file. The line should look something like this:
```OBJJ_COMPILER_FLAGS = [... , "SourceMap"];```
All browsers support source maps but at the moment Chrome as the best support.
Here is a short clip on what it looks like when stepping in the browser: http://mini.carlberg.org/dev/Objective-J-Debugging.mov
=> Full support for source map when debugging

Foundation/CPCoder.j
CPCoder provided unused and broken implementations for encodePoint:, encodeRect: and encodeSize:
This PR replaces these with a _CPRaiseInvalidAbstractInvocation
=> fixed: unused and broken code removed from CPCoder

Objective-J/CFPropertyList.js
The xml parser in the Node.js engine is more modern and can handle more cases. Our property list parser does not handle this. This fix makes the test cases for the property lists run on the Node.js engine.
=> Fixed: The property list test cases can now run on the Node engine.

Tools/nib2cib/NSTextField.j
As Cappuccino does not use cells a binding or connection made to a ```CPTextFieldCell``` will get lost when the Cib file is read as the cell is never stored in the Cib file.
This fix make sure that the binding / connection is made to the ```CPTextField``` instead of the cell by replacing the cell with the text field when reading the xib file. The same mechanism is used in ```NSButton``` and ```NSMatrix```.
This fix allows view based TableView bindings from a text field cell to the table cell view in the Interface Builder in Xcode.
This works in Cocoa.
=> Fixed: Nib2Cib will replace a CPTextFieldCell with a CPTextField

AppKit/_CPImageAndTextView.j
This call will crash as ```_DOMTextElement``` is ```nil```.
This check will make sure it is not called when no element is present. This is the same way as it is done in other parts of this class.
=> Fixed: Crash when triple click an empty CPTextField that is not editable but selectable

AppKit/Cib/_CPCibObjectData.j
If statement variable `instantiatedObject` on line 233 of
_CPCibObjectData.j overshadows a variable with the same name declared
on line 229 in the enclosing block. This variable is later added to array outside
the enclosing if statement, resulting in a potential loss of information.
Refs: #2601
=> Fixed: Variable in if statement overshadows variable in enclosing block

Foundation/CPProxy.j
Changed method selector parameter `selector` to `aSelector`, as that is the name of the variable used within the method.
=> Fix: CPProxy respondsToSelector incorrect parameter name

AppKit/CPSearchField.j
Variable `searches` is defined in the method selector, and then
redeclared with the `var` keyword two lines later. Removed the
redundant declaration, moving the variable assignment to its own line.
=> Formatting: removed redundant variable in CPSearchField.j

AppKit/CPColor.j
Variable `isVertical` is used throughout the function `patternColorsFromPattern` in CPColor.j despite never being declared.
Perhaps not necessary, in this pull request the variable `isVertical` is declared formally in the variable list before its use.
=> Formatting: formally declared variable before use in CPColor.j

AppKit/CPLevelIndicator.j
On lines 295 and 304, the selector for two method declarations are
followed by a semi-colon. Not sure if this causes problems or not, but
removed anyways.
=> Formatting: Remove semi-colon after method header in CPLevelIndicator

AppKit/CPRuleEditor/_CPRuleEditorViewSliceRow.j
Variable `ruleItems` is declared at the beginning of a variable declaration list, and then again at the end of the same list. Removed first occurrence.
=> Formatting: remove redundant variable in _CPRuleEditorViewSlice.j

AppKit/CPImage.j
Variable value assignment terminated in comma, despite not being a variable list. 
Replaced comma with semi-colon.
=> Formatting: add semi-colon to CPImage.j

AppKit/Platform/DOM/CPPlatformWindow+DOM.j
Missing semi-colon on line 1425.
Removed redundant `var` modifier on already declared variable on line
947.
Added variable declaration to variable used without declaration on line
970.
Removed redundant `var` modifier on already declared variable
`CPDOMEventGetClickCount` removed `var` on latter declaration as original
declaration has note stating it is to be declared at top so “so
compressor knows about them.”
=> Formatting: minor formatting updates in CPPlatformWindow+DOM.j

AppKit/CPTextView/CPTextView.j
previously, deleting text did not keep the selection visible under some circumstances.
this PR fixes that with a call to scrollRangeToVisible:
=> fixed: backspace did not trigger scrolling properly 927d6d2

AppKit/CoreAnimation/CPViewAnimator.j
Previously, the format for the matrix value of the transform property was matrix(a,b,c,d,tx,ty) where tx and ty had the "px" suffix. [According to Mozilla doc](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix) , tx and ty were accepted (in my understanding not required) with this suffix before FireFox 16 and required after.
All parameters are now numbers without suffix and this code is expected to work
with all FireFox versions supporting css animations.
=> Animating frame origin was not working on recent FireFox versions

AppKit/CPTabView.j
In CPTabView.j there was a mismatch on the variable name -- `_placeHolderView` vs `_placeholderView`. This pull request fixes this issue by using the variable name `_placeholderView` in all instances.
Fixes #2674
=> Fix: CPTabview placeholderView inconsistent variable name case

AppKit/CoreAnimation/_CPObjectAnimator.j
_CPObject animator labeled return type as BOOL, not only is this value not returned, but the super class CPProxy's initialize method returns void. Changed return type to void in _CPObject animator, to match superclass
=> Fixed: _CPObjectAnimator initialize method did not match superclass return

AppKit/CPScrollView.j, AppKit/CPScroller.j, AppKit/_CPPopUpList.j
Before this commit, CPScrollerView was not correctly differentiating the _scroller-width_ attribute value between the vertical scroller and the horizontal scroller.
The scroller width was picked from a common CPScroller instance cached in CPScroller and was incorrect for one of the two directions.
The bug was not visible because the method `-_adjustScrollerSize` is correcting the size at each  layout pass. However, this was causing unnecessary calls to `setFrame:` in a performance sensitive method triggered by scroll events.
The ScrollView is now picking the right width from the theme and the `setFrame:` call is skipped.
TESTS: Manual/CPScrollView2/
TODO : The `-_adjustScrollerSize` method should be enabled with a flag only when a width change is explicitly requested.
=> FIXED: CPScroller superfluous setFrame: calls

AppKit/Platform/DOM/CPPlatformWindow+DOM.j, Tests/Manual/TableTest/TableBindings/index.html
modern mobile browsers forbid to cancel touch events via preventDefault() by default.
this caused touch scrolling events to scrollviews to also scroll the document body.
this is fixed by this PR by means of providing the passive: false option.
i tested this on an ipad pro with both mobile safari and mobile firefox.
i also tested this on macbook pro chrome / firefox -> no issues
=> fixed: touch scrolling events to scrollviews also scrolled the document body

AppKit/CPTableView.j
Say you have a CPTableView with 3 columns, the rightmost one being partially masked like this : 
When you drag this column, the dragged view (or ghost view) is clipped : 
This PR fixes this by using columnRect width instead of columnVisRect width.
=> FIXED: Before this PR, when dragging a partially masked column, the dragged view was truncated

AppKit/CPTableView.j
Unfocused selected column should draw in unfocused selection color (gray). Before this, when dragging the column, it was using the focused selection color (blue), then returned to gray when drag ended.
This was due to an unconditional use of selectionHighlightColor.
This PR fixes this by conditionally using selectionHightlightColor or unfocusedSelectionHighlightColor.
=> FIXED: Before this PR, when an unfocused selected column was dragged, focused selection color was used

AppKit/CPCursor.j, Tests/Manual/CPCursor/AppController.j
This PR is originally aimed to fix a problem that was blocking the "grabbing hand" cursor (the one used when dragging things).
This is done by simply changing the string used "-moz-grabbing" to "grabbing".
Another name change is done for the "grab" (or open hand) cursor, from "move" to "grab".
Then, after reading NSCursor documentation, a new cursor is added : IBeamCursorForVerticalLayout
Then, in order to use modern Cocoa cursors, a new cursor creation method is proposed (very similar to the original one) : 
We now have 3 internal methods (instead of 1) :
```+ (CPCursor)_nativeSystemCursorWithName:(CPString)cursorName cssString:(CPString)aString``` 
This one is used when a direct system (browser) cursor exists, for example : crosshair
```+ …
```
=> FIXED: Before this PR, some cursors were badly or not displayed

AppKit/CPTableView.j
Say you have a table with a selected column, like : 
If you start dragging this column, the selection color remains on the freed space : 
This is because, when creating the dragged view (or ghost view), the "will be dragged" column was indeed unselected but without any refresh of the display.
This PR fixes this by simply adding a setNeedsDisplay:YES.
=> FIXED: Before this PR, when dragging a selected column, selection color remained in place (visual artefact)

AppKit/CPScrollView.j, Tests/AppKit/CPScrollViewTest.j
This will (un)set CPThemeStateFirstResponder on CPScrollView based on the content view.
For now, only CPTableView's can initiate first responder state on a CPScrollView (and only if there's no in-cell editing).
This should be adapted when global focus ring management will be added to Cappuccino.
With this PR, it's easy to add a focus ring around a CPScrollView containing a CPTableView which is the first responder of the window (this will be used by Aristo3).
=> NEW: Add first responder management based on content view to CPScrollView

Tools/nib2cib/NSTableHeaderView.j
Nib2Cib was forcing the header view height to the default-row-height attribute.
With this PR, if a header-view-height attribute value exists, Nib2Cib uses it. If not, Nib2Cib uses default-row-height attribute value, as before.
=> FIXED: Before this PR, Nib2Cib wasn't using theme attribute "header-view-height"

AppKit/CPTableHeaderView.j
Say you have a table with 50 rows. Scroll your table until you see row 30 on top of the visible rect like this :
Then start dragging a column left or right.
Your table will automatically scroll down until reaching the last row like this : 
The problem is in the way used to constrain the drag of the column to avoid autoscroll vertically.
The bug here is in the method `[view convertPoint:aPoint toView:aView]` : `aPoint` should be in the coordinate system of view and it is not.
This PR fixes this by always setting the vertical coordinate to the height of the header. This way, mouse is considered at the very top of the visible rect and starts then no autoscroll.
=> FIXED: Before this PR, starting a column drag within a scrolled down table would scroll the table content to the bottom

Objective-J/Runtime.js, Tests/Objective-J/MethodDispatchTest.j
Forwarding and Invocation worked also on the +initialize method.
To mimic Objective-C correctly the +initialize method should not be sent on a class hierarchy if it does not implement it.
Also the +initialize method should not allowed to be forwarded to another target with Invocation or any other forwarding mechanism.
Added test cases for this and cleaned up some test cases that succeeded for the wrong reason.
This change will not affect many projects as all classes inherit from CPObject.
=> Fixed: the class method +initialize was always sent even if the root class did not implement it.

AppKit/CPFontManager.j
previously we had duplicate method definitions in CPFontManager for convertFont:toHaveTrait: and convertFont:
these are removed by this PR
fixes #2816
=> fixed: removed outdated duplicate method definitions in CPFontManager.j

AppKit/CPCompatibility.j
before this PR, backspace and the arrow keys did not emit CPEvents anymore
this PR readjusts the cappuccino compatibility layer to the recent changes in FF.
=> fixed: FF66 does not emit CPEvents anymore for backspace, delete and the arrow keys

AppKit/CPCompatibility.j, AppKit/Platform/DOM/CPPlatformPasteboard.j
before this patch, the backspace key caused the page back action in firefox.
this is almost always unwanted by the user and not the case in chrome/safari.
this patches cancels the backspace event if no editing takes place.
=> Fixed: backspace triggered page back in FireFox

Foundation/CPDecimal.j, Tests/Foundation/CPDecimalNumberTest.j
previously, the code in CPDecimalDivide called a nonexistant function under certain conditions.
this is fixed by this PR
fixes #2818
=> fixed: typo in function call to _CPDecimalSetZero

Objective-J/Executable.js
The sourcemap was not included when building from command line with the release (the default) version of the tools. This results in compiled code without the source map included for debug
=> Fixed: If sourcemap is available include it when building with a nondebug version of the tools.

AppKit/CPTextView/CPTextView.j
previously, the whitespace on the pasteboard was not taken into account when preparing the smart paste.
this is corrected by this PR.
the bug was exposed on cappcon 2018 during the live demo ;-)
=> fixed: smart copy/paste cycle was leaving an additional whitespace on the LHS

AppKit/CPTableColumn.j, Tests/AppKit/CPTableViewTest.j
This prevents a buildup of large arrays with a lot of values and then choose one row and throw away the rest. This is great for speed and a must for lazy loading.
Previous there was a optimization for this but it was only effective for short combined key path like ```a.b```. This pull request makes it effective for any kind of length of a combined key path like ```a.b.c.d...```.
This is done by returning the object at a row in the first found CPArray in the key path
that is divided in a first and second part.
The first part is never a combined key path. The second part can be a combined key path.
If this optimization is not done we will create an array with the valueForKeyPath value on each row and then pick the wanted value for the row and throw away all the other rows. It is much more …
=> Fixed: Optimization for bindings with longer key paths in table views.

README.markdown
removed the wrong attribute 'demo' for our tutorials link
=> Formatting: make readme a little more concise

AppKit/CPBrowser.j, Objective-J/ObjJAcornCompiler.js, Objective-J/Runtime.js, Tests/Objective-J/Preprocessor/BehaviorTests/MethodTest.j, Tests/Objective-J/Preprocessor/OutputTests/Messages/colon-selector-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/colon-selector.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/complex-receiver-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/complex-receiver.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/keyword-in-selector-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/keyword-in-selector.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/multiple-parameters-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/multiple-parameters.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/no-parameters-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/no-parameters.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/one-parameter-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/one-parameter.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/self-as-receiver-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/self-as-receiver.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/ternary-operator-argument-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Messages/ternary-operator-argument.js, Tests/Objective-J/Preprocessor/OutputTests/Misc/parenthesis-return-inlined.js, Tests/Objective-J/Preprocessor/OutputTests/Misc/parenthesis-return.js
The ```msgSend``` function has always returned ```nil``` if the receiver has been ```nil``` or ```undefined```.
Example:
```
var a = undefined;
var b = [a someSelector]; // b = nil
```
The variable ```b``` is now ```nil```.
This pull request adds the ability for the ```msgSend``` function to return ```undefined``` if the receiver is ```undefined```. If the receiver is ```nil``` it still return ```nil```.
The above example again:
```
var a = undefined;
var b = [a someSelector]; // b = undefined
```
The variable ```b``` is now ```undefined```.
The use of ```nil``` in Objective-C corresponds to the use of ```null``` in C and C++ and stands for "no value". A fundamental function in Objective-C is when you send a message to a receiver that is ```nil``` the result is again a ```nil``` value. …
=> New: msgSend will return undefined instead of nil when the receiver is undefined [+1]

AppKit/Platform/DOM/CPPlatformWindow+DOM.j
the original implementation of CPPlatformWindow+DOM.j was faulty in two ways: firstly, _capsLockActive was accidentally a global variable, secondly, pressing capslock accidentally emitted keyDown:(CPEvent)events
both issues are fixed in this PR
=> fixed: pressing capslock inserted whitespaces under certain conditions

AppKit/CPArrayController.j, Tests/AppKit/CPArrayControllerTest.j
Previously, the filter predicate was removed on setContent: or on content binding. When this option is on, the FP should be removed only on insertion, as the name of the option suggests it.
With Tests: Foundation unit test.
fixes #2791
=> clearsFilterPredicateOnInsertion option is for insertion only

AppKit/CPTextField.j
There was a problem introduced by pull request #2600 when trying to select and copy text in a selectable text field. The problem only occurs when the text field is in a modal window.
It was caused by the modal run loop that is present as an eventListener on the CPApplication when in modal mode. It will force a bail out from the sendEvent: method in CPApplication when trying to handle the event. As the check for key equivalent is moved down by the #2600 pull request it will never be allowed to handle a copy command from the browser menu or key equivalent.
The solution is to allow the text field to handle the event if it is selectable. This will also allow the text selection to be altered from the keyboard with keys like shift-left/right/up/down arrow. Combinations like shift-option arrow …
=> Fixed: Let the text field handle key commands when it is selectable

AppKit/Platform/DOM/CPPlatformWindow+DOM.j
The default was to make the first window in the most background layer the key window if nothing else was used.
This does not work well if there is a modal window that should have all the attention.
This solution will first choose the modal window if in modal mode. If not the old variant is used.
=> Fixed: In modal mode a focus event will make the modal window the key window

Foundation/CPKeyValueObserving.j
This pull request adds a ```kvoValueForKey:``` method used by ```_CPKVOForwardingObserver``` for getting values.
The default action is to just return the ```valueForKey:``` value.
Override this method if you want any other behavior.
It can be used to just return ```nil``` if you are implementing a lazy load behavior on a class.
It can allow a combined binding to observe this object without trigger any lazy loading.
=> New: Allow lazy loading control for combined observer key paths

Foundation/CPSet/_CPSet.j, Tests/Foundation/CPSetTest.j
Test case also added.
Deprecated the very old behaviour that the block could return YES to abort the enumeration.
=> Fixed: CPSet enumerateObjectsUsingBlock: will honor the stop variable

AppKit/CPView.j, AppKit/CPWindow/CPWindow.j
This speed improvement is very notable when resizing a browser window of altering the size of
split views.
The fix uses a variable on the window to control when to update the tracking areas.
If the view is not connected to a window the tracking areas will not be updated as they will
be when added to a window.
=> Fixed: Update Tracking areas only once when doing setFrame: on a view

AppKit/CPView.j
This makes updating views much faster when they need layout. This will make resizing browser
window and changing split views sizes much smoother.
The effectiveAppearance is inherited from the superview. The superviews appearance is passed
along as it is recomputed down the view hierarchy.
Also the current appearance is saved on each view to make it possible to only change the theme
states when the appearance is changed.
=> Fixed: CPAppearance has better performance now when views needs layout

AppKit/CPTrackingArea.j, AppKit/CPView.j
Calculations of the visible rect can be a heavy operation as it depends of the superviews
visible rect. They have to be transformed and intersected together to create the result.
This calculation is a recursive operation that travels up the view hierarchy all the way
to the top.
Updating the tracking areas is also a recursive operation. But it travels down the view hierarchy
instead. It will calculate the new tracking area using the visible rect for the current view. For
each view it updates it will get the visible rect that has to travel all the way up the view
hierarchy to calculate it by transform and intersect them together. This results in that the visible
rect will be calculated for each view multible times. This makes it a very slow operation, specially
for deeper view hierarchies. …
=> Fixed: Performance improvement on visibleRect when updating tracking areas

AppKit/Platform/DOM/CPPlatformWindow+DOM.j, AppKit/Platform/DOM/CPPlatformWindow+DOMKeys.j
previously, wrong characters were emitted from keyDown: events in more recent Firefox versions. The reason is that keyCodes do not correspond to characters but rather refer to keys on the keyboard.
The bug is exposed in CPTextView that relies on keyDown: events. CPTextFields are not affected because they are based native input elements.
This patch uses the key property that corresponds to characters and not keys.
Works for me on FireFox, Safari and Chrome.
fixes #2873
=> Fixed: CPTextView keyboard issue in recent Firefox versions

Foundation/CPPredicate/CPComparisonPredicate.j, Tests/Foundation/CPPredicateTest.j
An example:
```
var array = @[ @{@"Name": @"1"},
@{@"Name": @"2", @"approveTime": @"Now"}
];
var predicate = [CPPredicate predicateWithFormat:@"approveTime != nil"];
CPLog(@"result: %@", [array filteredArrayUsingPredicate:predicate]); // result: <empty array>
```
If I run this in Cappuccino I get an empty array
If I run it in Cocoa on a Mac I get:
```
result: (
{
Name = 2;
approveTime = Now;
}
)
```
=> Fixed: CPPredicate does never evaluate to true for 'something != nil'

AppKit/Jakefile, AppKit/Themes/BlendKit/Jakefile, Foundation/Jakefile, Objective-J/CommonJS/lib/objective-j/compiler.js, Objective-J/Jakefile, Objective-J/ObjJAcornCompiler.js, Objective-J/OldBrowserCompatibility.js, Tests/Objective-J/Preprocessor/BehaviorTests/IvarTest.j, Tests/Tools/ToolsTest.j, Tools/nib2cib/Jakefile
I have used this feature for some time at our project and been able to find a few unknown bugs. Now is the time for it to reach a wider audience.
Please try it out and let me know if this is a good warning that should be added to our compiler
This new warning adds a lot of warnings in the Cappuccino frameworks. I have turned off
the warning in the Jakefiles when compiling most of the Cappuccino frameworks. But it is
on as default for any user projects.
So there is also a new feature to turn off/on warnings as a compiler flag.
These flags are (all flags are on as default):
-Wunused-but-set-variable                    Warning when a local variable is never read.
-Wshadow-ivar                                Warning when a local variable is shadowing an instance variable for the class. …
=> New: The compiler will now create warnings for variables that are never read

AppKit/CPButton.j, AppKit/_CPImageAndTextView.j
This PR simply uses the _usesSingleLineMode property of _CPImageAndTextView.
=> FIXED: Before this PR, CPButton never declares that its label should be single line

AppKit/CPTextField.j
This PR adapts the calculation of where in the textfield text the mouse is clicked to take in account the text alignment.
Before the PR:
After the PR:
=> FIXED: Before this PR, a click in a not first key responder CPTextField would misplace the caret if text alignment was not CPLeftTextAlignment

AppKit/CPTextView/CPLayoutManager.j
previously, CPTextView could crash under certain esoteric conditions from accessing properties of undefined.
this is fixed by this PR
=> fixed: _glyphsFrames and _glyphsOffsets could be used uninitialized

AppKit/CPView.j
A line from a manual merge was left in the code. This does not alter any functionality.
=> Fixed: Removed old unused line from a bad manual merge

Objective-J/ObjJAcornCompiler.js
The compiler will crash for really large Objective-J files as the array with code segments will hit this limit.
The solution is to append the array item by item.
I do not find any change on performance with this new implementation.
=> Fixed: JavaScriptCore (WebKit) has a limit at 65536 on number of arguments in a function.

AppKit/CoreAnimation/CPViewAnimator.j
```alphaValue``` is a float, not a CGPoint.
=> FIXED: This PR fixes correct parameter type in CPViewAnimator -setAlphaValue

AppKit/CPColor.j
Fixes a theme compilation problem because of lack of rgba capability of the compiler.
=> FIXED: Before this PR, theme color values with alpha component weren't correctly compiled

AppKit/CPImage.j
The classname for CSS theming was not specified in the correct DOM element.
=> FIXED: Before this PR, the classname was not specified in the correct DOM element

AppKit/CPColor.j, AppKit/CPView.j
+ (void)restorePreviousCSSState:(CPArrayRef)aPreviousStateRef forDOMElement:(DOMElement)aDOMElement
was declared as an instance method but must be a class method.
=> FIXED: CPColor restorePreviousCSSState method must be a class method

AppKit/Themes/BlendKit/BKThemeDescriptor.j, AppKit/_CPObject+Theme.j
This PR adds a class method to BKThemeDescriptor that enables a view to inherit theme values of another view.
This new method can be used in ThemeDescriptor.j
=> NEW: This PR adds a class method to BKThemeDescriptor that enables a view to inherit theme values of another view

AppKit/CPControl.j, AppKit/CPFont.j, AppKit/CPTheme.j
With this PR, you can now specify : 
- System font face
- System font sizes for regular, small and mini controls
- the CSS code to be injected in order to use specific fonts
For example, the following declaration is used in the ThemeDescriptors.j file of Aristo3 : 
```
+ (CPFont)themedFont
{
var font = [CPFont systemFontOfSize:12],
themeFontStyle = @"@font-face { font-family: 'SFNSText'; src: local('.SFNSText-Light'), url('%%/fonts/SFNSText-Light.woff') format('woff'); font-weight: 300 }\n"
+ @"@font-face { font-family: 'SFNSText'; src: local('.SFNSText-Medium'), url('%%/fonts/SFNSText-Medium.woff') format('woff'); font-weight: 500 }\n"
+ @"@font-face { font-family: 'SFNSDisplay'; src: local('.SFNSDisplay-Light'), url('%%/fonts/SFNSDisplay-Light.woff') format('woff'); font-weight: 300 …
```
=> NEW: This PR makes system font themable

Foundation/CPKeyedArchiver.j
Delegate methods described on lines 76 and 85 are not the selectors
checked on lines 305 and line 302, but are the methods actually called
on the delegate on lines 195 and 225. This fix updates the method
selectors checked on the delegate, to match those defined and called
within the CPKeyedArchiver class.
Fixes #2679
=> Fix: CPKeyedArchiver method call does not match selector tested

AppKit/_CPObject+Theme.j
Loading cached theme attributes will miss previous cached value if superclass is done before subclass
=> Fixed: Loading cached theme attributes will miss previous cached value.

AppKit/CPRadio.j, Tests/AppKit/CPButtonTest.j
The current Interface Builder mechanism relies on buttons having the same containing view and sharing an IBAction. Beyond those two requirements, everything is automatic.
This PR fixes #2901
=> FIXED: This PR supports modern Cocoa behavior regarding radio buttons groups.

AppKit/CPLevelIndicator.j, AppKit/CPSlider.j, Tools/nib2cib/NSSlider.j
- Modern Cocoa behavior and methods
- Ticked sliders
It implements the following methods : 
```
/*!
Creates and returns a continuous horizontal slider whose values range from 0.0 to 1.0.
@param aTarget
@param anAction
*/
+ (CPSlider)sliderWithTarget:(id)aTarget action:(SEL)anAction
// Creates and returns a continuous horizontal slider that represents values over the specified range.
+ (CPSlider)sliderWithValue:(double)value minValue:(double)minValue maxValue:(double)maxValue target:(id)target action:(SEL)action
// The knob’s thickness, in pixels.
// The thickness is defined to be the extent of the knob along the long dimension of the bar.
// In a vertical slider, a knob’s thickness is its height; in a horizontal slider, a knob’s thickness is its …
```
=> Aristo3: CPSlider

AppKit/CPControl.j
With #2920, CPButton's now set their font using [self font]. The corresponding adaptation in CPControl was missing in the previous PR.
=> FIXED: Before this PR, CPButton's won't display their title

AppKit/CPWindow/_CPPopoverWindowView.j, AppKit/_CPPopoverWindow.j
This introduces a Cappuccino specific behavior that permits to control the background color of the popover by setting a background color on the content view.
One can, using this, create "post-it" like yellow popovers : 
- Without doing anything (usual situation) : 
- After setting content view background to rgb 254, 246, 156 : 
- Without this PR (after setting content view background) :
=> NEW: This PR adds the ability to control CPPopoverWindow background color.

AppKit/CPScroller.j
Just added the bad value received.
This PR is not mandatory at all (but it's a very easy one).
=> NEW: This PR provides more information on an error message in CPScroller

AppKit/CPStepper.j
This bug was introduced by recent CPButton changes (#2920 and #2947).
This PR simply specifies correct CPButton bezel style to be used by steppers.
=> FIXED: Before this PR, CPStepper wouldn't display correctly

Tools/XcodeCapp/Jakefile
Fixed - compatibility check for building XcodeCapp depends on outmoded macOS version numbering scheme.
=> Fix version check for XcodeCapp compatibility with Big Sur

Tools/capp/Resources/Templates/Application/index-debug.html, Tools/capp/Resources/Templates/Application/index.html, Tools/capp/Resources/Templates/NibApplication/index-debug.html, Tools/capp/Resources/Templates/NibApplication/index.html, Tools/capp/Resources/Templates/ThemeDescriptor/index-debug.html, Tools/capp/Resources/Templates/ThemeDescriptor/index.html
Correct vertical alignment of loading animation in all modern browsers using CSS Flexbox layout.
IE is no longer a target.
=> Update "Loading…" animation using modern layout - Fixes Issue #2942

AppKit/CPRadio.j
This PR fixes a running condition where if the value is set before the radio button is associated in a radio group, the radio group will miss the currently selected button.
=> FIXED : This PR fixes a running condition that could occur in CPRadio

Tools/nib2cib/NSTabView.j
A call to ```[super awakeFromCib]``` was missing in nib2cib ```NSTabView.j``` (it was commented for tests in development branch).
This PR simply reintroduces this call.
=> FIXED: Before this PR, CPTabView was badly positioned 

Tests/AppKit/CPButtonTest.j
This pull request only adds a unit test that will Illustrate that value binding is not reversed set when another radio button is clicked.
=> New: Unit test to illustrate multiple value bindings on radio buttons

AppKit/CPTextView/CPTextView.j
This happens when the CPTextView is not editable and dragging a selected text.
=> Fixed: Prevent crash in CPTextView when _exposedRect is nil

AppKit/CPTextView/CPTextContainer.j, AppKit/CPTextView/CPTextView.j, Tools/nib2cib/NSTextContainer.j, Tools/nib2cib/NSTextView.j
The new options are:
1. Resizable Horizontally
2. Resizable Vertically
3. Max Size
Also two options from the Text Container is recognized:
1. Tracks text view width
2. Tracks text view height
The last two are needed to allow the text view to recalculate
the size of its content if the frame size is changed.
There are many more options we can add but it is out of the scope for this pull request.
=> Fixed: CPTextView now handles more options from Interface Builder

AppKit/Themes/Aristo2/ThemeDescriptors.j
This PR fixes #2984 
To cope with new control size management, we have to add some ```font``` attribute definitions to Aristo2.
=> FIXED: Before this PR, CPButton would always have the same label text size whatever the control size

AppKit/CPTextField.j
This PR simply adds a call to ```layoutSubviews``` after setting the text color.
Fixes #2985
=> FIXED: Before this PR, using setTextColor on a CPTextField would not take visual effect before an event

Tools/capp/Resources/Templates/NibApplication/AppController.j
Add commented-out code to capp gen NibApplication template.
The technique itself is easy to forget and not obvious to newcomers.
It is already included in the standard capp gen application template
and added here for completeness.
=> Include commented-out code to hide mainMenu in NibApplication template

AppKit/CPButton.j
If the bezel state was changed and some attribute was set like an "image". The image would not be found as there were two states active and it would not match.
=> Fixed: Bezel state ivar _bezelState must remove current state when changing to a new.

AppKit/CPView.j
This PR checks if there's a defined superview in ```resizeWithOldSuperviewSize```.
The problem can be observed when trying to nib2cib the MainMenu.xib file of the reduction in issue #2971 (ImageTest.zip).
=> FIXED: Before this PR, nib2cib would fail if, for some "not ready" condition, no superview is defined for a view

AppKit/CPWindow/CPWindow.j
previously, any app froze when clicking somewhere during sheet open/close animations.
these adversarial clicks are simply ignored by this PR.
fixes #3012
=> fixed: freeze when clicking during sheet animation

AppKit/CPBox.j
Warnings about borderColor, borderWidth, cornerRadius and fillColor are suppressed when boxType is CPBoxSeparator.
They are not relevant and needlessly clutter verbose output when debugging and should be suppressed.
Inline documentation for property handling is expanded to provide context for dropping of support for Groove and Bezel borderTypes and OldStyle and Secondary boxTypes.
=> CPBox: Suppress superfluous warnings and expand documentation

AppKit/CPColorPanel.j
using eval for parsing JSON is considered bad practice and is also slower.
addresses some of the concerns raised in #3013
=> fixed: usage of eval instead of JSON.parse for parsing JSON

Tools/capp/Resources/Templates/Application/index-debug.html, Tools/capp/Resources/Templates/Application/index.html, Tools/capp/Resources/Templates/NibApplication/index-debug.html, Tools/capp/Resources/Templates/NibApplication/index.html, Tools/capp/Resources/Templates/ThemeDescriptor/index-debug.html, Tools/capp/Resources/Templates/ThemeDescriptor/index.html
Replace `document.write(loadingHTML);` (which should be avoided for speed) with equivalent `innerHTML` code. If acceptable, the other templates (Application, Framework, ThemeDescriptor) might be upgraded accordingly.
=> Modernise "document.write" in «index.html» to "innerHTML"

AppKit/CoreGraphics/CGContextCanvas.j
As CGContextSetShadow wasn't initializing the shadow color to standard ```[CPColor shadowColor]```, the shadow color was still null, thus disabling shadowing in Canvas.
This PR simply adds the needed shadow initialization.
=> FIXED: Before this PR, CGContextSetShadow wasn't initializing the shadow color

AppKit/CPBox.j
=> FIXED: Before this PR, CPBox followed the autoresizesSubviews flags while Cocoa NSBox always autoresizes its subviews, whatever the flag is set to.

AppKit/CPSegmentedControl.j, AppKit/CPStringDrawing.j, AppKit/CPTextField.j, AppKit/CPTextView/CPTypesetter.j, AppKit/Platform/DOM/CPPlatformString.j, AppKit/_CPToolTip.j, Tests/Manual/CPTextView/AppController.j
see bug https://bugs.chromium.org/p/chromium/issues/detail?id=1192834.
This bug induces white gaps after heavy editing in CPTextViews using chrome/canary/chromium.
This PR makes cappuccino test whether canvas text sizing is functional.
If not so, cappuccino falls back to dom-based sizing
=> fixed: width of text sizing was slightly off in chrome

Tools/imagesize/imagesize.m
This PR simply uses ```NSImageRep``` ```pixelsWide``` and ```pixelsHigh``` methods to get correct sizes.
Please note that this PR only impacts CIB based applications as for code created images, size is either specified manually, either determined using the HTML IMG object ```width``` and ```height``` attributes, so in pixels size.
=> FIXED: Before this PR, imagesize would provide image size in points (that is, taking care of the image resolution) instead of pixels

Tools/nib2cib/NSTextView.j
nib2cib can fail and crash if a CPTextView is in the .xib file as the text view is not initialized correctly
=> Fixed: Correct init of CPTextView when running nib2cib

AppKit/CPScrollView.j, AppKit/CPScroller.j
Old deprecated api did not work as it was accessing ivars _horizontalScroller and _verticalScroller from class method.
New Cocoa api is added as described in Apple Developer Documentation.
Also added type CPScrollerStyle
=> Fixed: New Cocoa api that replace old deprecated for calculating size of scroll view

AppKit/CPTextView/CPTextView.j
previously, å and Å had been awkwardly filtered in keyDown: and reinserted via the deadkey handler. this caused a sluggish typing experience for our Skandinavian friends.
this filtering is cleaned up by this PR.
deadkey-diacritics still work.
tested on chrome, safari and FF, although only on mac.
fixes #3030
=> fixed: å and Å did not work well on scandinavian keyboards in CPTextView

AppKit/CPView.j
This typo occurs only once, line #3462 references the correct spelling.
=> CPView.j, fix typo: _ephereralSubviews → _ephemeralSubviews

Tools/XcodeCapp/Jakefile
Individual new OS releases had support added individually until now.
=> Allow building XcodeCapp under any version greater than Sierra

bootstrap.sh
Remove newly-unsupported linker flag
As per inline notes, this is a minimally intrusive hot fix for clang linker flag changes under Xcode 15
=> Fix narwhal-jsc build under Sonoma

Tools/capp_lint/capp_lint, Tools/capp_lint/install.sh
Requires Python 2, but this is true for XcodeCapp also. Installs to /usr/bin/local, but must be manually installed using install script in source directory.
=> Re-enable installation of capp_lint

AppKit/CPTokenField.j
this bug was introduced by commit 26aab29
26aab29 was meant to improve iOS experience but makes the tokenfield loose FR status prematurely.
this PR helps CPTokenField to regain FR status after bluring the inputfield by clicking on a token.
it secondly compensates for the backspace event not being propagated anymore in all circumstances
fixes #2795
=> fixed: selection and backspace are recently broken in CPTokenField

AppKit/CPSlider.j
This fixes bindings to also work when 'only stop at tick marks' is selected; formerly the code would crash silently with `setObjectValue`.
=> fixied: bindings for case  'only stop at tick marks'

README.markdown
General refinements.
Move npm quickstart instructions to a more prominent position.
Add licensing FAQ.
Add FAQ for porting code from Objective-C to Objective-J
=> README refinements

Tools/XcodeCapp/XcodeCapp/Images.xcassets/status-icon-inactive.imageset/Contents.json
Allows macOS to automatically manage blending mode and color of menubar icon.
Modern macOS renders the menubar with translucency, making icons with some fixed colors difficult to see with some wallpapers.
This was particularly pronounced with ‘status-icon-inactive’. 
Changing render mode to ‘Template Image’ allows the OS to adjust icon color and blending mode dynamically — to suit current combination of Light/Dark mode and wallpaper color.
=> Change rendering mode for menubar inactive icon from ‘Render As’ to ‘Template Image’

AppKit/CPDragServer.j
My application utilizes a CPTableView with relatively large (height-wise) rows (holding image thumbnails), and dragging and dropping rows within a CPScrollView is quite painfully slow.
This change adjusts the inset bounds for the scroll area from a hard-coded value of 30 pixels to be dependent on the row height of the CPTableView, if the target of the drag-and-drop is a CPTableView.
This works quite well for my application and seems relatively close to the Cocoa behaviour (subjectively, as I haven't been able to track down any documentation describing how this is actually implemented in Cocoa), but I'm open to alternative suggestions if this doesn't seem like the right approach.
There was an earlier discussion on this some months back (see …
=> If target view of a drag and drop is a CPTableView, set inset bounds based on the row height of the table

Foundation/CPArray/_CPJavaScriptArray.j, Foundation/CPData.j, Foundation/CPDate.j, Foundation/CPDictionary.j, Foundation/CPError.j, Foundation/CPException.j, Foundation/CPNumber.j, Foundation/CPString.j, Foundation/CPURL.j, Tests/Foundation/CPArrayTest.j
As we have a tool-free bridges between many classes and JavaScript types by setting the isa property on the type, for example Array and CPArray. Using the for...in enumeration the isa property will be included in the loop if the property is enumerable (this is the default behavior). This commit set the property as not enumerable.
=> Fixed: Make the isa property on classes not enumerable.

Foundation/CPTimeZone.j, Tests/Foundation/CPTimeZoneTest.j
=> fixed: CPTimeZone initWithName: does not return the timeZone with the good daylight saving

AppKit/Platform/CPPlatformWindow.j, AppKit/Platform/DOM/CPPlatformWindow+DOM.j
With these changes, two-finger touch scrolling will now have a pleasant and intuitive momentum effect, significantly enhancing the feel of your application on touch-enabled devices.
=> fixed: touch scrolling did not support momentum
